name: EduardWarp
description: Tutorial do Plugin de Warp
main: net.eduard.simplewarp.Main
version: 1.0
author: Eduard
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  warp:
    usage: /<command> help
    aliases: [delwarp,setwarp,warps]
    permission: warp.use
