name: EduardTapeteVoador
description: Sistema de Tapete que flutua (Baseado no MagicCarpet)
main: net.eduard.tapetevoador.Main
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  tapete:
    description: Ativar e Desativar o Tapete Voador