name: EduardCaixas
description: Tutorial de Caixas Misteriosas
main: net.eduard.misterybox.Main
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  comando:
    aliases: [dg]
    permission: perm.use
    permission-message: No Permission
    usage: /<command> [usage]
    description: Comando Description
