name: EduardSimplesPunir
description: Tutorial de Sistema basico de punir
main: net.eduard.simplespunir.Main
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  punir:
